// Generates one OpenComputer project per model from agent-template/.
// Each project has a single agent "dev" with its model fixed in code, so every
// session of that project runs the same model.
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { ROSTER } from "../lib/roster.ts";

for (const r of ROSTER) {
  const root = `projects/${r.key}`;
  const dir = `${root}/opencomputer/agents/dev`;
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(`${root}/opencomputer`, { recursive: true });
  cpSync("agent-template", dir, { recursive: true });
  writeFileSync(`${dir}/agent.ts`, readFileSync(`${dir}/agent.ts`, "utf8").replace("__MODEL__", r.model));
  writeFileSync(`${dir}/opencomputer.toml`, `# Generated by scripts/gen-agents.ts. Keep \`id\` stable across deployments.\nschema = 1\nid = "dev"\nname = "Agent Picks (${r.label})"\n`);
  writeFileSync(`${root}/opencomputer/project.ts`, `export default {\n  name: "agent-picks-${r.key}",\n  agents: ["dev"],\n};\n`);
  writeFileSync(`${root}/opencomputer/.env.example`, readFileSync("opencomputer/.env.example", "utf8"));
  if (existsSync("opencomputer/.env.local")) writeFileSync(`${root}/opencomputer/.env.local`, readFileSync("opencomputer/.env.local", "utf8"));
  // The CLI resolves @opencomputer/agent from the project; share the root install.
  if (!existsSync(`${root}/node_modules`)) symlinkSync("../../node_modules", `${root}/node_modules`);
  if (!existsSync(`${root}/package.json`)) writeFileSync(`${root}/package.json`, JSON.stringify({ name: `agent-picks-${r.key}`, private: true, type: "module" }, null, 2) + "\n");
}
console.log("generated", ROSTER.map((r) => r.key).join(", "));
