// Generates one coding agent per model, opencomputer/agents/dev-<key>/, from agent-template/,
// and writes opencomputer/project.ts. Each agent's model is fixed in code. Tool and
// connection names get a per-agent suffix because they must be unique within a project.
// The orchestrator, opencomputer/agents/agentpicks/, is hand-written and listed first so
// its cloud agent id is the project's own id; the coding agents are "<id>--dev-<key>".
import { cpSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROSTER } from "../lib/roster.ts";

const NAMES = ["web_fetch", "report_choice"];

function rewrite(dir: string, key: string, model: string) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) { rewrite(p, key, model); continue; }
    if (!/\.(ts|toml|json)$/.test(f)) continue;
    let s = readFileSync(p, "utf8").replace(`useModel("__MODEL__")`, `useModel("${model}")`);
    for (const n of NAMES) s = s.replace(new RegExp(`\\b${n}\\b`, "g"), `${n}_${key}`);
    writeFileSync(p, s);
  }
}

for (const r of ROSTER) {
  const dir = `opencomputer/agents/dev-${r.key}`;
  rmSync(dir, { recursive: true, force: true });
  cpSync("agent-template", dir, { recursive: true });
  rewrite(dir, r.key, r.model);
  writeFileSync(`${dir}/opencomputer.toml`, `# Generated by scripts/gen-agents.ts. Keep \`id\` stable across deployments.\nschema = 1\nid = "dev-${r.key}"\nname = "Coding agent (${r.label})"\n`);
}
writeFileSync(
  "opencomputer/project.ts",
  `// Generated by scripts/gen-agents.ts.\nexport default {\n  name: "agentpicks",\n  agents: ${JSON.stringify(["agentpicks", ...ROSTER.map((r) => `dev-${r.key}`)])},\n};\n`,
);
console.log("generated", ROSTER.map((r) => `dev-${r.key}`).join(", "));
